### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Eluviian** [UAlbertaALTLab/morphodict-frontend#12]
![settings](https://user-images.githubusercontent.com/77465461/210668777-2ba33f25-ba08-40ec-a04a-776108bec3d7.png)

-"Settings" title needs to be smaller, maybe bolded, more padding above and below

-"Paradigm labels" needs to be changed to "Display Mode", text underneath also needs to be changed
-Examples need to be italicized
-"Show Morpheme Boundaries" needs to be changed to "Morpheme Boundaries", text underneath also has slight difference
-small differences in a lot of the text, will not list them all here

For every section:
-Text under title of section needs to be smaller
-Different label types need to be bolded ("Plain English labels", etc)
-Eliminate grey lines in between choices
-Bullet for selected choice looks different - should be filled with blue with thin blue border hovering above

**Comment by nienna73** [comment]
Fonts have been updated in PR #27

**Comment by nienna73** [comment]
Resolved in PR #39
