### ISSUE TITLE
Search results are inconsistent

### ISSUE THREAD

**Issue by nienna73** [UAlbertaALTLab/morphodict-frontend#22]
The first few search results work just fine, but the more you search, the more nonsense you get. For example:

<img width="1438" alt="Screen Shot 2023-01-31 at 10 48 22 AM" src="https://user-images.githubusercontent.com/28357720/215841947-cfc62093-4965-4954-8fa3-924ded3f8840.png">

There are a few possible culprits of this issue:
1. The backend is wrong
2. We're searching too soon in the query. As in, we send the query "ma" to the backend instead of the full query "maskwa". This could be solved with a `debounce` function
3. We don't rerun the query when the user finishes typing. This is related to (2), but relates to when the user is done typing their query as opposed to still typing.
4. The searching and analysis are happening in the wrong order (should analyze then search)

**Comment by nienna73** [comment]
The solution related to theory number 2: we were searching too early in the typing sequence and that search wouldn't get interrupted or overridden when a new string was entered. The solution, for now, is to only perform search when the Enter key is pressed or the magnifying glass icon is pressed.

**Comment by aarppe** [comment]
This *still* does not work, cf.

https://github.com/UAlbertaALTLab/morphodict-frontend/assets/15003407/436239ce-2b30-4159-ba3b-f8ab896c69ec

**Comment by Eluviian** [comment]
This appears to be resolved. Waiting for more testing before I close the issue
