### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by Eluviian** [UAlbertaALTLab/morphodict-frontend#6]
![Searchbar - app](https://user-images.githubusercontent.com/77465461/210662002-cd09c99f-8d08-4efb-8d58-803ab0cbe355.png)
![Searchbar - dev](https://user-images.githubusercontent.com/77465461/210662008-37a5a463-a568-41e3-aa64-bf4142df1e79.png)

Change look of search bar
-Should not be captioned "Search"
-Should have magnifying glass icon on the right
-Corners should be more rounded
-Height needs to be shorter, and should be longer horizontally
-Interior of search box should be white, not grey
-Change font to match app version, and increase font size

**Comment by Eluviian** [comment]
![search bar - search message - dev](https://user-images.githubusercontent.com/77465461/210668629-beed79f1-d700-4f70-9c80-201bb375e210.png)
![search bar - search message - app](https://user-images.githubusercontent.com/77465461/210668640-d8300f87-8353-42de-b5fe-12f4c9112aa5.png)

Default message needs to be changed to "Search in Cree or English"
-Font size needs to be adjusted, needs to be italicized

**Comment by nienna73** [comment]
Everything except the syllabics have been fixed in PR #26. Syllabics are being moved to a new issue.
