### ISSUE TITLE
Use same font in search bar as elsewhere

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict-frontend#64]
Multiple fonts give a confused look.

Production:
<img width="621" alt="image" src="https://github.com/UAlbertaALTLab/morphodict-frontend/assets/15003407/1d47d0f3-d8fa-480a-ac4a-1fc68d1c3f1d">

Refactored:
<img width="624" alt="image" src="https://github.com/UAlbertaALTLab/morphodict-frontend/assets/15003407/3b2ffd7b-e5a8-4673-98cc-2d18625ce521">

**Comment by Eluviian** [comment]
As I mentioned, there is an issue where the font is different on Mac. This was changed and deployed some time ago, below is what it looks like on my Windows machine. I will be investigating this week why the font works only on some operating systems.

![image](https://github.com/UAlbertaALTLab/morphodict-frontend/assets/77465461/e2763b63-3ae4-4168-9866-d77e410393db)
