### ISSUE TITLE
Info Icon

### ISSUE THREAD

**Issue by Eluviian** [UAlbertaALTLab/morphodict-frontend#7]
![info icon - dev](https://user-images.githubusercontent.com/77465461/210663550-82ce8bbf-1088-4340-a90f-11dac10ed4a7.png)
![info icon - app](https://user-images.githubusercontent.com/77465461/210663570-39610a8d-ffba-478a-b649-fc722189a870.png)

Change Appearance of Info Icon:
-Needs to be larger, and blue instead of black
-Needs to be located next to search result (in same line instead of above)

![info icon - dev - mouse over](https://user-images.githubusercontent.com/77465461/210663609-21e59060-8ebd-412f-89d3-317a9097182d.png)
![info icon - app - mouse over](https://user-images.githubusercontent.com/77465461/210663618-37bd19ad-751a-4f5a-8ed9-7cb07600f258.png)

When moused over:
-Pop-up should be white and opaque, instead of black and semi-transparent
-Pop-up should be shorter in height and wider in length
-Text should be black instead of white
-Text should start at "Action word...", take away search result at beginning of this

**Comment by Eluviian** [comment]
Maybe the "moused over" part of this should be changed into it's own issue - I see that this is also the case when other items are moused over

**Comment by nienna73** [comment]
@Eluviian Could you add a new entry for the mouse over differences like you mention above? Thanks!

**Comment by nienna73** [comment]
Moving the "moused over" part to a new issue. Everything else was resolved in PR #26
